config/routes.rb
Rails.application.routes.draw do

  resources :critters, only: [:index, :show]
  resources :collections

  get ':name', to: 'types#show', as: :type
  root to: "pages#home"
end

app/models/api.rb
require 'httparty'

class Api
    URL = "https://acnhapi.com/v1a/"

    def self.get_critters(type_slug)
        critters = HTTParty.get("#{URL}#{type_slug}")
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collection.rb
class Collection < ApplicationRecord
    has_many :critter_collections
    has_many :critters, through: :critter_collections

    validates :name, uniqueness: true
end

app/models/critter.rb
class Critter < ActiveRecord::Base
    belongs_to :type
    has_many :critter_collections
    has_many :collections, through: :critter_collections

    validates :name, uniqueness: true

    def self.create_from_result(result, type_id)
        Critter.create(
            name: result["name"]["name-USen"],
            location: type_id == 3 ? "sea" : result["availability"]["location"],
            rarity: result["availability"]["rarity"],
            icon_uri: result["icon_uri"],
            type_id: type_id
        )
    end

end

app/models/critter_collection.rb
class CritterCollection < ApplicationRecord
    belongs_to :critter
    belongs_to :collection
end

app/models/type.rb
class Type < ActiveRecord::Base
    has_many :critters

    validates :name, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController

    def index
        @collections = Collection.all
    end

    def new
        @collection = Collection.new
    end

    def create
        @collection = Collection.new(collection_params)
        @collection.save
        redirect_to collection_path(@collection)
    end

    def show
        @collection = Collection.find_by(id: params[:id])
    end

    def edit
        @collection = Collection.find_by(id: params[:id])
    end

    def update
        @collection = Collection.find_by(id: params[:id])
        @collection.update(collection_params)
        redirect_to collection_path(@collection)
    end

    def destroy
        @collection = Collection.find_by(id: params[:id])
        if @collection
            @collection.destroy
        end
        redirect_to collections_path
    end

    private

    def collection_params
        params.require(:collection).permit(:name)
    end

end

app/controllers/critters_controller.rb
class CrittersController < ApplicationController

    def index
        @critters = Critter.all
    end

    def show
        @critter = Critter.find(params[:id])
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
        render :home
    end

end

app/helpers/application_helper.rb
module ApplicationHelper



end

app/views/collections/edit.html.erb
<h2>Edit Collection</h2>

<div class="row">
    <div class="col s12 l3">
        <%= form_for @collection do |f| %>
        <%= f.text_field :name %>
    </div>
        <div class="col">
            <%= f.submit "Update Name", class: "btn" %>
            <% end %>
        </div>
</div>

<div class="row">
    <div class="col s12 l3">
      <div class="row">
        <div class="input-field col s12">
          <input type="text" id="autocomplete-input" class="autocomplete">
          <label for="autocomplete-input">Add new critter</label>
        </div>
      </div>
    </div>
  </div>


<%= link_to "Delete", @collection, method: "delete" %>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.autocomplete');
    var instances = M.Autocomplete.init(elems, options);
  });
</script>

app/views/collections/index.html.erb
<h2>Collections</h2>

<p><%= link_to "New Collection", new_collection_path, class: "teal-text text-lighten-2" %></p>

<div class="row">
    <% @collections.each do |c| %>
    <div class="col s12 m4">
      <div class="card">
        <div class="card-content">
          <span class="card-title teal-text text-lighten-2"><%= c.name %></span>
          <p><%= c.critters.count %> critters</p>
        </div>
        <div class="card-action teal lighten-3">
            <%= link_to "View", collection_path(c), class: "white-text" %>
            <%= link_to "Edit", edit_collection_path(c), class: "white-text" %>
            <%= link_to "Delete", collection_path(c), method: :delete, class: "white-text" %>
        </div>
      </div>
    </div>
    <% end %>
</div>

app/views/collections/new.html.erb
<h2>New Collection</h2>

<div class="row">
    <div class="col s12 l3">
        <%= form_for @collection do |f| %>
        <div class="input-field">
            <%= f.text_field :name %>
            <label for="collection_name">Name</label>
        </div>
        <%= f.submit "Create Collection", class: "btn" %>
        <% end %>
    </div>
</div>

app/views/collections/show.html.erb
<h1><%= @collection.name %></h1>

<p><%= link_to "Edit Collection", edit_collection_path, class: "teal-text text-lighten-2" %></p>
<p><%= link_to "Collection Index", collections_path, class: "teal-text text-lighten-2" %></p>

<div class="row">
<% @collection.critters.each do |critter| %>
    <div class="col s1 m4">
        <div class="card">
            <div class="card-image">
                <img src="<%= critter.icon_uri %>" alt="<%= critter.name %> icon">
                <span class="card-title teal-text text-lighten-2">
                    <%= critter.name %>
                </span>
            </div>
            <div class="card-action teal lighten-3">
                <%= link_to "View", critter_path(critter), class: "white-text" %>
            </div>
        </div>
    </div>
<% end %>
</div>

app/views/critters/index.html.erb
<h2>All Critters</h2>

<div class="row">
<% @critters.each do |critter| %>
    <div class="col s1 m4">
        <div class="card">
            <div class="card-image">
                <img src="<%= critter.icon_uri %>" alt="<%= critter.name %> icon">
                <span class="card-title teal-text text-lighten-2">
                    <%= critter.name %>
                </span>
                
            </div>
            <div class="card-action teal lighten-3">
                <%= link_to "View", critter_path(critter), class: "white-text" %>
                <%= link_to "Add to Collection", critter_path(critter), class: "white-text" %>
            </div>
        </div>
    </div>
<% end %>
</div>

app/views/critters/show.html.erb
<h2><%= @critter.name %></h2>

<img src="<%= @critter.icon_uri %>" alt="<%= @critter.name %> icon">

<p><strong>Location:</strong> <%= @critter.location %></p>
<p><strong>Rarity:</strong> <%= @critter.rarity %></p>

<%= link_to "<< All Critters", critters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>

  <nav class="teal lighten-2">
    <div class="nav-wrapper container">
      <a href="#" class="brand-logo">Animal Crossing Critterpedia Lite</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="/critters">Critters</a></li>
        <li><a href="/collections">Collections</a></li>
      </ul>
    </div>
  </nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
    <h1>Welcome to Critterpedia Lite!</h1>